USE [ABS_LMS]
GO

/****** Object:  Table [dbo].[Client]    Script Date: 23/09/2016 11:15:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Client](
	[ClientId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Client] PRIMARY KEY CLUSTERED 
(
	[ClientId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


INSERT INTO CLIENT VALUES ('AAL')
GO
INSERT INTO CLIENT VALUES ('ACL')
GO
INSERT INTO CLIENT VALUES ('ACS')
GO
INSERT INTO CLIENT VALUES ('ACS-PROFESSIONAL SERVICES')
GO
INSERT INTO CLIENT VALUES ('admin')
GO
INSERT INTO CLIENT VALUES ('AEL')
GO
INSERT INTO CLIENT VALUES ('ITSL')
GO
INSERT INTO CLIENT VALUES ('SCL')
GO
